[package]
name = "djvu_nav"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.11"
crossterm = "0.27"
nom = "7.1.3"
ratatui = "0.25"
unicode-width = "0.1.10"
